- xml/entity-decl.ent
- xml/s4s_autoyast.xml
- xml/s4s_installation_sap.xml
This PR provides:
* Mention SUSE Manager in the unattended installation of the OS section, pointing to the right chapters
* Adds a section about installing SAP products with automated installation
* Provides example snippets for the SAP product section
* Makes reference to a full HANA example now included in the sap-installation wizard package.
> Document unattended installation of SAP products, including reference to SUSE Manager

- xml/s4s_encrypt.xml
* Distinguish between successful and unsuccessful entries.
> Fix FATE#322292: allow remote mount/umount

- xml/s4s_tune.xml
This PR fixes bsc#1119254 ("[doc] warn about possible conflicts"):
* Rephrase note
> Clarify tip/note

- xml/s4s_tune.xml
* Add new sections about customizing, creating, showing, verifying, and simulating SAP notes
* Change wording of  "Profile" to "Solution" in section ID=sec.s4s.saptune.enable as requested by Sören
* Delete block entries starting with SUSE-GUIDE in section ID=sec.s4s.saptune.enable
* Correct list of manpages
* Fix link to GH of `saptune`
For link to Etherpad, see bsc#1140720. Thanks to Sören Schmidt! :+1:
> Add review about saptune

- xml/s4s_planning.xml
According to the bug, it applies to:
> Fix bsc#1154579: Improve supported POWER architectures

- DC-SLES4SAP-guide
- xml/MAIN-SLES4SAP-guide.xml
- xml/common_copyright_gfdl.xml
- xml/common_intro_feedback_i.xml
- xml/common_intro_typografie_i.xml
- xml/entity-decl.ent
- xml/s4s_about.xml
- xml/s4s_appendix_cryptoaddon.xml
- xml/s4s_appendix_docupdates.xml
- xml/s4s_components.xml
- xml/s4s_configuration.xml
- xml/s4s_install_network.xml
- xml/s4s_installation.xml
- xml/s4s_installation_sap.xml
- xml/s4s_overview.xml
- xml/s4s_partitioning.xml
- xml/s4s_qinstall.xml
* Converted DocBook4 sources to DocBook5 with the [migration script](https://github.com/sknorr/daps-migrate-tools/blob/master/migrate2docbook5.sh)
* Adapted `STYLEROOT` in DC file.
Tested:
* Run `daps -d DC-SLES4SAP-guide validate` which was ok.
* Run `daps -v -d DC-SLES4SAP-guide pdf` which created a PDF; looked good.
> Convert SLES for SAP11 SP4 to DocBook5

- xml/s4s_tune.xml
This PR fixes https://jira.suse.com/browse/PM-1346 and contains a description for:
* `saptune note delete`
* `saptune note rename`
Co-authored-by: Sören Schmidt <scmschmidt>
---
Screenshot:
> Add commands "delete" & "rename" for saptune

- xml/s4s_tune.xml
* A brief "table" which shows profiles for tuned in/with sapconf 4/5
* Mention SLE15 and remove "and above"
@scmschmidt what do you think?
> Add overview about sapconf4/5 in SLE12/15

- xml/s4s_access.xml
* Replaces SUSEFirewall2 with firewalld
* Adds a note taken from doc-sle (`security_firewall.xml`)
> Replace SUSEFirewall2 to firewalld (bsc#1175712)

- xml/s4s_components.xml
This PR contains a fix for [SLE-10758](https://jira.suse.com/browse/SLE-10758):
* updated link to GitHub repo
I've checked the section (ID=sec-component-clustertool in file `s4s_components.xml`), but as the explanation was very general (no specific command lines) I didn't change anything there.
> Fix outdated ClusterTools2 (jira#SLE-10758)

- xml/s4s_planning.xml
Regarding section "Overview of the Installation Workflow":
In SLES for SAP15, the package `sles-release` is available, making this important notice obsolete. It's still needed for
SLE12.
> Fix bsc#1153487: Remove important note

- xml/art_solution_automation.xml
- Makes clear that SALT formulas is fully supported
- Removes mention of terraform not being supported, since it is now part of the Public Cloud Module
> Clarification about support of each component

- xml/art_solution_monitoring.xml
The exporters are part of SLES for SAP and fully supported by SUSE.
> Removing support mentioning

- xml/s4s_tune.xml
Distinguishes between different sapconf versions:
* Use /var/lib/sapconf/act_profile for sapconf 5.0.0
* Use /run/sapconf_act_profile for sapconf >= 5.0.1
Related to [bsc#1179885](https://bugzilla.suse.com/show_bug.cgi?id=1179885).
> Fix bsc#1179885: Distinguish sapconf versions

- xml/art_solution_automation.xml
This PR contains the following changes:
* Rephrase note text about official support
* Move GitHub links into "For more information" section
Once all is confirmed, cherry-pick into:
----
> Improve note and GitHub links

- xml/art_solution_automation.xml
- xml/s4s_components.xml
This PR removes the link to the private GH link.
Needs to be backported to:
* `maintenance/15_GA`
* `maintenance/15_SP1`
* `maintenance/15_SP2`
> Fix bsc1183550 and remove private GitHub link

- xml/s4s_partitioning.xml
Use SAP note 2578899 instead of 1984787.
Cherry-pick it to:
* `maintenance/15_GA`: 
* `maintenance/15_SP1`: 
* `maintenance/15_SP2`:
> Fix bsc#1182953: correct wrong SAP note

- xml/s4s_tune_wmp.xml
The next update for the sapwmp package will introduce a change due to a altered behaviour of the SAP kernel in latest versions. As a result sapstartsrv will no longer be moved to the SAP.slice.
Adapt the "Reboot and verifcation" section
Fix DOCTEAM-147 / bsc#1184874
----
> sapstartsrv is no longer moved to SAP.slice

- xml/s4s_tune_wmp.xml
sapstartsrv is no longer moved to SAP.slice
@scmschmidt: Could you have a look? I also found the `sapstartsrv` string in the same file, but in a different line. I also replaced them with `sapstart`. However, I'm not sure if this was correct so I changed that so you can see them in the diff.
With this commit, I couldn't find any further `sapstartsrv` strings in other files.
> Remove sapstartsrv and use sapstart

- xml/s4s_planning.xml
This PR fixes [bsc#1188243](https://bugzilla.suse.com/show_bug.cgi?id=1188243)
Only Intel 64 is supported. Neither Intel ia64 nor AMD64 are supported by SAP for HANA.
Needed for:
* `maintenance/15_SP3`
* `maintenance/15_SP2`
* `maintenance/15_SP1`
* `maintenance/15_GA`
* `maintenance/12_SP5`
* `maintenance/12_SP4`
* `maintenance/12_SP3`
> Use "Intel 64" as supported CPU

- l10n/ja-jp/guide/xml/MAIN-SLES4SAP-guide.xml
- l10n/ja-jp/quick/xml/MAIN-SLES4SAP-guide.xml
reset dm:component to "Documentation" 15 SP3 for all languages
will be done for each  version branch so no backport needed
> SEO: reset dm:component SLESforSAP 15 SP3

- l10n/ja-jp/guide/xml/MAIN-SLES4SAP-guide.xml
- l10n/ja-jp/quick/xml/MAIN-SLES4SAP-guide.xml
dm:editurls tag removed for all languages of SLE 15 SP3.
Will be done for each branch version separately therefore no backports needed.
> SEO: edit urls removed l10n SLESforSAP 15SP3

- l10n/ja-jp/guide/xml/MAIN-SLES4SAP-guide.xml
- l10n/ja-jp/quick/xml/MAIN-SLES4SAP-guide.xml
dm:editurls tag removed for all languages of SLES for SAP 15 SP2.
Will be done for each branch version separately therefore no backports needed
> remove edit urls l10n SLESforSAP15SP2

- xml/s4s_installation.xml
Pattern name `patterns-sles-sap_server` was renamed to `patterns-server-enterprise-sap_server`
Thanks to Bernd Schubert!
> Fix bsc#1190426: Rename pattern name

- xml/s4s_upgrade_sap_hana_cluster.xml
* a new step to ensure passwordless SSH access
Reference: [bsc#1191537](https://bugzilla.suse.com/show_bug.cgi?id=1191537)
> Fix bsc#1191537: add pre-requisites for update wizard

- xml/article_sap_trento.xml
* Take into account KUBECONFIG environment variable
* Take care user that installed K3s for the Trento Server container using Helm
This is how the procedure looks like now:
Co-authored-by Alberto Bravo <abravosuse@users.noreply.github.com>
> Add missing installation steps for Trento Server

- xml/article_sap_trento.xml
This PR fixes #107 
**Hint**: Although correct, the diff might be a bit confusing. I had to rework the procedures for the Updating the Trento Agents a bit as copy-and-paste does not really work.
It might be easier to review the screenshots below.
<details>
<summary>Section Updating Trento Server (click me)</summary>
</details>
<details>
<summary>Section Updating Trento Agents (click me)</summary>
</details>
> Correct update section for Trento Server and Agents

- xml/article_sap_trento.xml
This PR fixes #106 and contains the changes for the new Trento Premium version. See the screenshot:
> Fix #106: Correct install cmd for Trento Server

- xml/article_sap_trento.xml
Replace TRENTO_SERVER_HOSTNAME with trento-server in helm upgrade command in both install and update sections.
> Replace TRENTO_SERVER_HOSTNAME

- xml/article_sap_trento.xml
In the installation and update instructions for Trento Server premium, update the Trento helm chart version from 0.3.5 to 0.4.3.
> Trento helm chart version 0.4.3

- xml/article_sap_trento.xml
Update Trento server installation instructions to use Trento server chart version 0.4.4, for the installation of Trento server 0.9.1
> Trento server 0.9.1

- xml/article_sap_trento.xml
The Trento premium installation package is available for customer that don't have a Kubernetes in place and want to deploy it on K3s on SLES for SAP.
---
---
After the PR is merged, cherry-pick to `maintenance/15-SP3`.
> Make clear when to use trento-premium package

- xml/article_sap_trento.xml
As discussed in our [2022-03-16 meeting](https://confluence.suse.com/display/TRNT/2022-03-16+Trento+Documentation),  this introduces a short explanation of the _Report feedback_ button on the Trento server home page.
I haven't inserted a screenshot (yet) as I wasn't sure if this would be stable the feedback form is.
---
> Introduce feedback option

- xml/article_sap_trento.xml
Indicating that the experimental flag is not needed as of helm version 3.8.0.
> Helm experimental flag

- xml/article_sap_trento.xml
Remove version flag from installation and update process of Trento Server (no longer needed).
> Remove version flag

- xml/article_sap_trento.xml
Adding port TCP/9100 as a network requirement
> Port required to reach Node Exporter

- xml/MAIN-SLES4SAP-guide.xml
- xml/article_sap_automation.xml
- xml/article_sap_monitoring.xml
- xml/book_solution_based.xml
- xml/product-entities.ent
- xml/s4s_image.xml
- xml/s4s_installation.xml
Introduce `&productnameshort;` entity as discussed in SLE Writers Call on 2022-11-21.
Dima, if you are okay with the change, I will take care of cherry-picking it into the different branches.
The first commit (0998779) introduces just the entity and adds it into the `<info>` element. The second commit (bd3b1f5) goes one step further and uses this newly introduced entity all over the document. I've separated the commits to make it (hopefully) easier to cherry-pick them.
* DOCTEAM-828
- SLES-SAP 15
- SLES-SAP 12
> Introduce &productnameshort; entity

- xml/s4s_upgrade_sap_hana_cluster.xml
Change two instances of "... an &hana ..." to "... a &hana ..." so that it reads better - note previously submitted & fixed via #97
N/A
- SLES-SAP 15
- SLES-SAP 12
> Fix grammar in s4s_upgrade_sap_hana_cluster.xml v2

- .gitignore
- doc-kit.conf
- xml/common_intro_convention.xml
- xml/common_intro_support.xml
- xml/generic-entities.ent
Updating the files provided by doc-kit to (mainly to include the latest updates for the common intro* files). As agreed with @dmpop,I skipped the doc-kit updates for common_intro_available_doc.xml as this has SLES-SAP specific content here.
> doc-kit run for 15 SP4 (fetch updates)

- .gitignore
- doc-kit.conf
- xml/common_intro_convention.xml
- xml/common_intro_support.xml
- xml/generic-entities.ent
Updating the files provided by doc-kit to (mainly to include the latest updates for the common intro* files). As agreed with @dmpop, I skipped the doc-kit updates for common_intro_available_doc.xml as this has SLES-SAP specific content here.
> doc-kit run for 15 SP3 (fetch updates)

- .gitignore
- doc-kit.conf
- xml/common_intro_convention.xml
- xml/common_intro_support.xml
- xml/generic-entities.ent
Updating the files provided by doc-kit to (mainly to include the latest updates for the common intro* files). As agreed with @dmpop, I skipped the doc-kit updates for common_intro_available_doc.xml as this has SLES-SAP specific content here.
> doc-kit run for 15 SP2 (fetch updates)

- xml/s4s_about.xml
Integrate proofing corrections for the Installation Quick Start Guide from proofing drop 3.
- SLES-SAP 15
- SLES-SAP 12
> Installation QS Guide: integrate proofing corrections

- xml/common_intro_support.xml
- xml/s4s_about.xml
- xml/s4s_installation.xml
- xml/s4s_tune_wmp.xml
Integrate proofing corrections for the SAP Guide from proofing drop 3.
- SLES-SAP 15
- SLES-SAP 12
> SAP Guide: integrate proofing corrections

- xml/MAIN-SLES4SAP-guide.xml
- xml/article_sap_automation.xml
- xml/article_sap_monitoring.xml
Add some basic metadata, so the tasks view and the filing of the docs as "Product Documentation" work. Currently just for main.
* bsc#...
* jsc#...
- SLES-SAP 15
- [x ] 15 next *(current `main`, no backport necessary)*
- SLES-SAP 12
> adding basic metadata for portal testing

- xml/MAIN-SLES4SAP-guide.xml
- xml/article_sap_automation.xml
- xml/article_sap_monitoring.xml
Add final metadata.
Based on multiple cherrypicks from 'main':
* 7168c53d83fe1e9800b5b805d85252e56a616cea
* 475fbeca4d6aaee1932e377798c8ce71aab181dc
* 7b8f18148f3dd297b7b3c7d6485b1d56c2abdb50
* cdb323874e75ef8224c6a8a1df447538473ca26a
* ff8077508f06c04a11d21feb809821a48167d460
* a8f7ab2b33f5f9bf49a280914e8e16a13e858037
* 1b7d512ab5186fc15e0a1558456f5ca17a817cd1
(original PR: https://github.com/SUSE/doc-slesforsap/pull/176)
Revhistory needs to be backported in a separate commit, because the data differs from branch to branch. 
- SLES-SAP 15
- SLES-SAP 12
> add final metadata for 15 SP5

- DC-SLES-SAP-sol-automation
- DC-SLES-SAP-sol-monitoring
- DC-SLES4SAP-guide
- DC-SLES4SAP-quick
This change switches the validation schema from GeekoDoc to DocBook 5.2. This ensures that futures changes of GeekoDoc doesn't affect previous, now unsupported documents.
related to https://gitlab.suse.de/susedoc/docserv-config/-/merge_requests/510
- SLES-SAP 15
- SLES-SAP 12
no backport necessary
> EOL SLES4SAP 15 SP1: Switch validation to DocBook 5.2

- xml/article_sap_automation.xml
- xml/article_sap_monitoring.xml
- xml/product-entities.ent
- xml/s4s_autoyast.xml
With the upcoming version 5.1, **SUSE Manager** will be renamed to **SUSE Multi-Linux Manager** (already released SuMa versions keep their name and their documentation URLs).
The SLE 15 SP7 documentation needs to reflect the product name change. 
Also, the 'generic' URL `https://documentation.suse.com/suma` (which always redirects to the docs for the latest released SuMa version) will be replaced with `https://documentation.suse.com/multi-linux-manager` moving forward.
https://jira.suse.com/browse/DOCTEAM-1754
- SLES-SAP 15
15 SP7 only - NO backports to older versions!
> Product renaming (SuMa -> SMLM)
