SUSE/doc-slesforsap

xml/s4s_appendix_docupdates.xml
xml/s4s_setup_cluster.xml

@sknorr : Please review (and add docupdate entry, if needed).

fixes bsc#1086628 (misleading sentence)

---

xml/s4s_installation.xml

This PR contains the following changes:
* Fix bsc#1125271
* Integrate commit b56843e2a about migrate-sles-to-sles4sap package

Fix bsc#1125271: Add former TID 7018744

---

xml/entity-decl.ent
xml/s4s_planning.xml

This PR fixes bsc#1111975 and contains:
* Insert a new section that points to SLES Upgrade Guide at www.suse.com

Add New Section about Offline Migration

---

xml/s4s_appendix_extrasoftware.xml

* Mention `/etc/os-release` and refer to TID#7023490
* Describe `/etc/products.d/baseproduct` and recommend xmlstarlet for extracting information

Fix bsc#1154168 and describe CPE_NAME/cpeid

---

DC-SLES-SAP-sol-automation
DC-SLES-SAP-sol-monitoring
xml/art_solution_automation.xml
xml/art_solution_monitoring.xml
xml/book_solution_based.xml
xml/common_copyright_quick.xml
xml/generic-entities.ent
xml/product-entities.ent

This PR relates to [Jira#SLE-8983](https://jira.suse.com/browse/SLE-8983) and contains:
* Add DC files
* Add two files with `<article>` as root
* Add a main file which uses `<book>` as root (`<set>` would also be possible)
* Is independent from the other main file
@taroth21 This is a first structure, just to let you know.

First structure on solution based doc for SAP

---

xml/s4s_tune.xml

Add multi-queue schedulers for sapconf (SLE15)

---

xml/s4s_tune.xml

* Mention SLES in conjunction with SLES for SAP
* Use PROFILE placeholder in `/usr/lib/tuned/PROFILE/tuned.conf`
* Add ID `pro-sapconf-4-configure` and title for procedure
* Adapt some sentence to align with SLE12 maintenance branch

Apply changes from SLE12 to SLE15

---

xml/s4s_components.xml
xml/s4s_tune.xml

Add multi-queue schedulers for sapconf (SLE12)

---

xml/s4s_tune.xml

SLES4SAP = SLES for SAP Applications

Mention SLES in conjuction of SLES4SAP

---

xml/s4s_tune.xml

* Mention SLES in conjuction with SLES4SAP
* Create a general note before first sect1
* Remove the two notes inside the specific sections for sapconf4 and sapconf5

Improve note admons and mention SLES

---

xml/art_solution_automation.xml

This PR contains changes in regards to the SAP Automation guide:
* Add missing link for upstream GitHub project on DRBD/NFS formula
* Hint customer to upstream projects for additional documentation

Fix bsc#1174530 DRBD/NFS Automated Configuration

---

xml/s4s_setup_cluster.xml

This PR contains a link to:
* Guide:
"SAP HANA System Replication Scale-Up - Performance Optimized Scenario"
* Section:
"Implementing the Python Hook SAPHanaSR"
https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-15/index.html#_implementing_the_python_hook_saphanasr

Fix bsc#1176096: Add link to SBP regarding srHooks

---

xml/art_solution_automation.xml
xml/common_intro_feedback.xml
xml/generic-entities.ent
xml/product-entities.ent

* a new section "Using Salt Formulas" and a procedure on how to apply formulas
* describes both ways: Salt master/minion and Salt minion only
PDF with remarks:
[art-sol-automation_remarks_color_draft_en.pdf](https://github.com/SUSE/doc-slesforsap/files/5266711/art-sol-automation_remarks_color_draft_en.pdf)
------
@arbulu89 Would you like to have a look? :wink: I've added some remarks and questions, maybe you could answer them in the review. See page 4ff.
I took the freedom to change some steps slightly from your original post. The reason for this was to make it more consistent and to make it easier to read.

Fix #39: Using Salt Formulas 

---

xml/art_solution_automation.xml

* Shift focus towards NFS than DRBD
* Copy paragraph about habootstrap-formula
* Add links
* Stay consistent with the other sections
----
Looks like this:
---
@arbulu89 What do you think? Does it fit better into the doc now? :wink:

Fix #40: Adjust section about DRBD/NFS

---

xml/s4s_tune.xml
xml/s4s_tune_wmp.xml

* Conversion from ADoc file into DocBook5
* Adapt structural changes
Related to https://jira.suse.com/browse/PM-1093

Rework "Tuning Workload Memory Protection" section

---

xml/s4s_components.xml
xml/s4s_remoteaccess.xml

This PR contains the following changes:
* Use `firewall-cmd` command
* Replace SUSEfirewall2 with firewalld

Fix bsc#1180154: Replace SUSEfirewall2

---

xml/s4s_tune.xml

The text was already there, I just added some examples and added a list of important points to remember.
Taken from [Sören's text](https://jira.suse.com/secure/attachment/118431/Details%20for%20delete%2Brename).
No review needed, just minor improvements.

Improve jira#SLE-10764: saptune delete/rename

---

xml/common_intro_available_doc.xml
xml/s4s_about.xml
xml/s4s_overview.xml

Trying to streamline the book intros like we did for SLE.
See: 
- https://github.com/SUSE/doc-sle/pull/778
- https://github.com/SUSE/doc-sle/pull/779
- https://github.com/SUSE/doc-sle/pull/780
- https://github.com/SUSE/doc-sle/pull/781

Streamline Intros

---

xml/s4s_tune_wmp.xml

Fixes bsc#1184871
For SLES for SAP 15 SP2

Add POWER as another supported arch to WMP

---

xml/product-entities.ent
xml/s4s_tune_wmp.xml

Improves consistent spelling for bsc#1184876

Create &wmp; entity (fix bsc#1184876)

---

xml/s4s_tune_wmp.xml

Fixes DOCTEAM-153 / bsc#1184879
Needs to be cherry-picked to:

Remove lines with sapstartsrv processes

---

xml/s4s_tune_wmp.xml

Correct sapwmp.conf (DOCTEAM-152)

---

.travis.yml
DC-SLES-SAP-guide
DC-SLES-SAP-quick
DC-SLES-SAP-sol-automation
DC-SLES-SAP-sol-monitoring

Adjust DC files for SLE* to use the new stylesheets (branding update).
jsc#SLE-15711

branding update: suse2013-ns -> suse2021-ns

---

xml/s4s_tune.xml

Fix DOCTEAM-175 / bsc\#1185770
Needs to be integrated in:
----

Add section about sapconf_check

---

xml/s4s_tune.xml

* Add additional entry NETWEAVER+HANA to the list.
* Disable "(identical to...)" hints. ATM, I use a comment, just in case.

Fix bsc#1187051 and list additional entry for saptune

---

xml/s4s_appendix_extrasoftware.xml
xml/s4s_components.xml
xml/s4s_planning.xml
xml/s4s_tune.xml
xml/s4s_tune_wmp.xml

These are the original proofing changes that I accidentally committed to `main`.
I have reverted that, and recovered the mistaken commit into a new branch.
Snag: now Github thinks the desired changes are older than `main` and I cannot create a PR; it wants me to pull the changes from `main` into my branch. I do **not** want that.
Poor solution: Reflow all files with daps-xmlformat so Github believes they are newer.
This is the result. My apologies for the ugly and uninformative diff.

Incorporate proofreading changes into main SLES4SAP Guide

---

xml/s4s_tune.xml

Additional info in a paragraph. Needs to be cherry-picked to:
Co-authored-by: Sören Schmidt <scmschmidt@users.noreply.github.com>

Fix bsc#1192548 more info about saptune update

---

xml/article_sap_trento.xml

This PR fixes the following issues discussed in our meeting from 2021-12-16:
* Change title
* Add admonition to warn users about discrepancies between current installation procedure and future RPM package installation
* Remove "cliffhanger" paragraph
* Use "discovered" instead of "registered"
* [CFSA-327](https://jira.suse.com/browse/CFSA-327)

Fix issues from CFSA-327

---

xml/s4s_upgrade_sap_hana_cluster.xml

Change two instances of "... an SAP HANA ..." to "... a SAP HANA ..." so that it reads better.

Fix grammar in s4s_upgrade_sap_hana_cluster.xml

---

xml/article_sap_trento.xml

Fix #104
Co-authored-by: Alberto Bravo <abravosuse@users.noreply.github.com>

Require env variable for Trento server install

---

xml/article_sap_trento.xml

Update trento server requirements with storage requirements

Trento server requirements

---

xml/article_sap_trento.xml

Corrections to installation procedure and other minor errors.

Corrections to installation procedure

---

xml/MAIN-SLES4SAP-guide.xml

SEO fix broken link for SLES for SAP 12 SP3

SEO fix link SLES4SAP 12 SP3

---

xml/s4s_clamsap.xml
xml/s4s_setup_cluster.xml
xml/s4s_tune.xml
xml/s4s_tune_wmp.xml
xml/s4s_upgrade_sap_hana_cluster.xml

Integrated proofing corrections for the SLES SAP Guide from VT.

SLES SAP guide proofing integration

---

xml/article_sap_automation.xml

Update the Salt procedure

---

xml/article_sap_trento.xml

Option to customize the alerting email sender address,

Alerting email sender customization

---

xml/article_sap_trento.xml

Warning about not using K3s for production purposes

Not using K3s for production purposes

---

xml/MAIN-SLES4SAP-guide.xml
xml/product-entities.ent

Bump product numbers and adjust Bugzilla pointers in the docs.

Prepare infrastructure for upcoming Service Pack

---

doc-kit.conf
xml/common_intro_feedback.xml
xml/common_license_gfdl1.2.xml
xml/generic-entities.ent
xml/network-entities.ent

Update files from latest doc-kit to include the description of the feedback icons in the book intros.
* bsc#...
* jsc#DOCTEAM-804
- SLES-SAP 15
- SLES-SAP 12

run doc-kit update (intro icons)

---

xml/article_sap_monitoring.xml

Add a chapter covering the HANA DB exporter.
* jsc#DOCTEAM-902
- SLES-SAP 15
- SLES-SAP 12

HANA DB Exporter

---

xml/s4s_installation.xml

SLES4SAP Quick Start review before GMC.

SLES4SAP Quick Start review

---

xml/s4s_tune_wmp.xml

Update the WMP-related content
* PED-4368
- SLES-SAP 15
- SLES-SAP 12

Deprecate WMP

---

xml/s4s_tune.xml

Update saptune 3.1
* DOCTEAM-1108
- SLES-SAP 15
- SLES-SAP 12

saptune update

---

xml/s4s_tune.xml

Fix DOCTEAM-1178
Describe the overall goal of this pull request.
* bsc#...
* jsc#...
- SLES-SAP 15
- SLES-SAP 12

Amend the text

---

xml/s4s_appendix_extrasoftware.xml
xml/s4s_appendix_win_cheatsheet.xml

Fix broken links and replace `http` by `https` protocol where feasible.
- see also https://github.com/SUSE/doc-sle/pull/1635 
- SLES-SAP 15
- SLES-SAP 12

Fix broken links

---

xml/MAIN-SLES4SAP-guide.xml
xml/article_sap_automation.xml
xml/article_sap_monitoring.xml

SLES-SAP is included in the portal prototype. Adding the final metadata and the revision history
* bsc#...
* jsc#...
- SLES-SAP 15
- SLES-SAP 12

Add missing metadata

---

xml/MAIN-SLES4SAP-guide.xml

Add final metadata.
Based on https://github.com/SUSE/doc-slesforsap/pull/176.
- SLES-SAP 12

Metadata backport for 12 SP5

---

xml/s4s_about.xml
xml/s4s_components.xml

Integrate proofing corrections for the Installation Quick Start Guide from proofing drop 3.
- SLES-SAP 15
- SLES-SAP 12

Installation QS: integrate proofing corrections

---

l10n/ja-jp/guide/xml/MAIN-SLES4SAP-guide.xml
l10n/ja-jp/quick/xml/MAIN-SLES4SAP-guide.xml

Correct some metadata strings that should not have been translated in the first place. 
Link to our [internal page](https://confluence.suse.com/pages/viewpage.action?pageId=1559986235).
- SLES-SAP 15

Fix localized metadata for SLES-SAP 15 SP6

---

l10n/ja-jp/guide/xml/MAIN-SLES4SAP-guide.xml
l10n/ja-jp/quick/xml/MAIN-SLES4SAP-guide.xml

1.  Add its namespace to root element
2.  Add localized metadata
Link to our [internal page](https://confluence.suse.com/pages/viewpage.action?pageId=1559986235).
- SLES-SAP 15

Add localized metadata for SLES-SAP 15 SP5

---

l10n/ja-jp/guide/xml/MAIN-SLES4SAP-guide.xml
l10n/ja-jp/quick/xml/MAIN-SLES4SAP-guide.xml

1.  Add its namespace to root element
2.  Add localized metadata
Link to our [internal page](https://confluence.suse.com/pages/viewpage.action?pageId=1559986235).
- SLES-SAP 15

Add localized metadata for SLES-SAP 15 SP3

---

l10n/ja-jp/guide/xml/MAIN-SLES4SAP-guide.xml
l10n/ja-jp/quick/xml/MAIN-SLES4SAP-guide.xml

1.  Add its namespace to root element
2.  Add localized metadata
Link to our [internal page](https://confluence.suse.com/pages/viewpage.action?pageId=1559986235).
- SLES-SAP 15

Add localized metadata for SLES-SAP 15 SP2

---

xml/article_sap_monitoring.xml

Improve the `Create a new user with the monitoring role` chapter to put a more accurate example of what the user must do.
* bsc#1235623 (not strictly related, the fix comes due some work in this bug)
- SLES-SAP 15
- SLES-SAP 12

Improve user monitoring role creation chapter in SAP monitoring

---

xml/MAIN-SLES4SAP-guide.xml
xml/article_sap_automation.xml
xml/article_sap_monitoring.xml

Set date in revision history to FCS date for 15 SP7 and keep initial entry as agreed with @lvicoun.
the documentation that your PR applies to.
- SLES-SAP 15

Revision History: initial entry for FCS of 15 SP7 

---

xml/s4s_access.xml

Add content covering DNS over TLS and DNS over HTTPS
* PED-8334
- SLES-SAP 15
- SLES-SAP 12

Improve DNS communication security

---

doc-kit.conf
xml/book_solution_based.xml
xml/common_copyright_gfdl.xml
xml/common_intro_convention.xml
xml/common_intro_feedback.xml
xml/common_legal.xml
xml/common_license_gfdl1.2.xml
xml/generic-entities.ent
xml/s4s_about.xml
xml/s4s_access.xml
xml/s4s_appendix_extrasoftware.xml
xml/s4s_appendix_partition.xml
xml/s4s_appendix_supplement.xml
xml/s4s_appendix_win_cheatsheet.xml
xml/s4s_clamsap.xml
xml/s4s_image.xml
xml/s4s_install_network.xml
xml/s4s_installation.xml
xml/s4s_installation_sap.xml
xml/s4s_overview.xml
xml/s4s_planning.xml
xml/s4s_remoteaccess.xml
xml/s4s_setup_cluster.xml
xml/s4s_trouble.xml
xml/s4s_tune.xml
xml/s4s_tune_wmp.xml
xml/s4s_upgrade_sap_hana_cluster.xml

SP7 only, each branch needs a separate PR

Adding a revision date to all chapters/parts
